name: Biên dịch dự án và tạo release
on: 
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    name: Biên dịch dự án và tạo release
    runs-on: windows-latest
    env:
      SolutionPath: ModThanhLC.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore the solution
        run: msbuild $env:SolutionPath /t:restore /p:Configuration=Release
      - name: Restore NuGet packages
        run: nuget restore $env:SolutionPath
      - name: Biên dịch dự án
        run: msbuild $env:SolutionPath /t:rebuild /p:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.action_ref }}
          path: Output
      - name: Nén artifact
        run: Compress-Archive -Path Output -DestinationPath "DragonBall.Pro.2.3.7.${{ github.ref_name }}.zip"
      - name: Phát hành artifact
        uses: softprops/action-gh-release@v2
        with:
          files: DragonBall.Pro.2.3.7.${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}-GHA
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}-GHA
