name: Biên dịch dự án và tạo release
on: 
  workflow_dispatch:
  push:
permissions:
  contents: write

jobs:
  build:
    name: Biên dịch dự án và tạo release
    runs-on: windows-latest
    env:
      SolutionPath: ModThanhLC.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore the solution
        run: msbuild $env:SolutionPath /t:restore /p:Configuration=Release
      - name: Restore NuGet packages
        run: nuget restore $env:SolutionPath
      - name: Biên dịch dự án
        run: msbuild $env:SolutionPath /t:rebuild /p:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Output
          path: Output
      - name: Nén artifact
        run: Compress-Archive -Path Output -DestinationPath "DragonBall.Pro.2.3.7.${{ github.ref_name }}.zip"
      - name: Phát hành artifact
        uses: softprops/action-gh-release@v2
        with:
          files: DragonBall.Pro.2.3.7.${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}-GHA
          draft: false
          prerelease: true
          tag_name: ${{ github.ref_name }}-GHA
          body: Bản phát hành này được tự động tạo từ mã nguồn bằng GitHub Actions. Nếu bản phát hành này ở trạng thái Prelease (màu cam), điều đó có nghĩa là đây là phiên bản thử nghiệm chưa được kiểm tra. Sử dụng phiên bản này có thể gây ra lỗi không mong muốn. Hãy chắc chắn rằng bạn đã sao lưu dữ liệu trước khi sử dụng phiên bản này.
